// <auto-generated />
using System;
using Labb3_SchoolDb_Alex.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb3_SchoolDb_Alex.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250127195934_InitialString")]
    partial class InitialString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927C0BDC1271F");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("CourseId")
                        .HasName("PK__Courses__C92D71A77BF25C93");

                    b.HasIndex("ClassId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04F1101209D35");

                    b.HasIndex("ProfessionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Grade1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Grade");

                    b.Property<DateOnly>("GradeSetDate")
                        .HasColumnType("date");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId")
                        .HasName("PK__Grades__54F87A5786F4A305");

                    b.HasIndex("CourseId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Profession", b =>
                {
                    b.Property<int>("ProfessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessionId"));

                    b.Property<string>("ProfessionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ProfessionId")
                        .HasName("PK__Professi__3F309E3F757F5A5B");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SocialSecurityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52B99C839A55F");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Class", b =>
                {
                    b.HasOne("Labb3_SchoolDb_Alex.Migrations.Employee", "Employee")
                        .WithMany("Classes")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Classes__Employe__3C69FB99");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Course", b =>
                {
                    b.HasOne("Labb3_SchoolDb_Alex.Migrations.Class", "Class")
                        .WithMany("Courses")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Courses__ClassId__4316F928");

                    b.HasOne("Labb3_SchoolDb_Alex.Migrations.Employee", "Employee")
                        .WithMany("Courses")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Courses__Employe__4222D4EF");

                    b.Navigation("Class");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Employee", b =>
                {
                    b.HasOne("Labb3_SchoolDb_Alex.Migrations.Profession", "Profession")
                        .WithMany("Employees")
                        .HasForeignKey("ProfessionId")
                        .IsRequired()
                        .HasConstraintName("FK__Employees__Profe__398D8EEE");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Grade", b =>
                {
                    b.HasOne("Labb3_SchoolDb_Alex.Migrations.Course", "Course")
                        .WithMany("Grades")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Grades__CourseId__47DBAE45");

                    b.HasOne("Labb3_SchoolDb_Alex.Migrations.Employee", "Employee")
                        .WithMany("Grades")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Grades__Employee__46E78A0C");

                    b.HasOne("Labb3_SchoolDb_Alex.Migrations.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Grades__StudentI__45F365D3");

                    b.Navigation("Course");

                    b.Navigation("Employee");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Student", b =>
                {
                    b.HasOne("Labb3_SchoolDb_Alex.Migrations.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Students__ClassI__3F466844");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Class", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Course", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Employee", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Courses");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Profession", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Labb3_SchoolDb_Alex.Migrations.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
